name = "backend-res"
main = "src/index.ts"
compatibility_date = "2024-12-26"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWVJHRzY1NFlCOUdaOTJaV1pWMTNFU0ciLCJ0ZW5hbnRfaWQiOiI0OWYyOTE5MWNiZmI2OWI0MGNlMDQ3ZmUxNzg0NDRkOGY0Yzc2OWM1YjRlYmM2MzFiZjNkYmQ4OTEzYzY3YmQ2IiwiaW50ZXJuYWxfc2VjcmV0IjoiODdmYzI1Y2MtNjA1OS00MmQ1LThkOWYtOWU3OTYwZjMzYjY2In0.5FQao8xCSeXB3dKA8OJ-HKRdOQWLoV478Ag6n1hbvis"
SECRETKEY_JWT = "MySecretPassword"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1